version: 2.1

orbs:
  docker: circleci/docker@2.1.1
  kubernetes: circleci/kubernetes@1.3.0

jobs:
  test:
    docker:
      - image: cimg/node:18.0.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-packages-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          paths:
            - ~/.npm
          key: npm-packages-{{ checksum "package-lock.json" }}
      - run:
          name: Run tests
          command: npm test
      - store_test_results:
          path: test-results

  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - docker/build:
          image: ${DOCKER_LOGIN}/${CIRCLE_PROJECT_REPONAME}-frontend
          tag: ${CIRCLE_SHA1}
      - docker/push:
          image: ${DOCKER_LOGIN}/${CIRCLE_PROJECT_REPONAME}-frontend
          tag: ${CIRCLE_SHA1}

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - kubernetes/create-or-update-resource:
          resource-file: k8s/deployments/frontend.yaml
          resource-name: deployment/frontend
      - kubernetes/create-or-update-resource:
          resource-file: k8s/services/frontend.yaml
          resource-name: service/frontend

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test
      - build-and-push:
          requires:
            - test
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build-and-push
          filters:
            branches:
              only: main