version: 2.1

orbs:
  digitalocean: digitalocean/cli@2.1.1

jobs:
  test:
    docker:
      - image: cimg/node:18.0.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-packages-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          paths:
            - ~/.npm
          key: npm-packages-{{ checksum "package-lock.json" }}
      - run:
          name: Run tests
          command: npm test
      - store_test_results:
          path: test-results

  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - digitalocean/install-cli
      - digitalocean/initialize
      - run:
          name: Build and push Docker image
          command: |
            docker build -t ${DIGITALOCEAN_REGISTRY}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} .
            docker push ${DIGITALOCEAN_REGISTRY}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - digitalocean/install-cli
      - digitalocean/initialize
      - run:
          name: Deploy to DigitalOcean Kubernetes
          command: |
            doctl kubernetes cluster kubeconfig save ${DIGITALOCEAN_CLUSTER_NAME}
            kubectl set image deployment/frontend frontend=${DIGITALOCEAN_REGISTRY}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}
            kubectl rollout status deployment/frontend

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test
      - build-and-push:
          requires:
            - test
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build-and-push
          filters:
            branches:
              only: main